[package]
name = "slow-query-converter"
version = "0.2.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
csv = "1.3.0"
chrono = "0.4.38"
regex = "1.10.4"
once_cell = "1.19.0"

