name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            ext: ''
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            ext: '.exe'
          - target: x86_64-apple-darwin
            os: macos-latest
            ext: ''
          - target: aarch64-apple-darwin
            os: macos-latest
            ext: ''

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ matrix.target }}-
            ${{ runner.os }}-cargo-

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Strip binary (Unix)
        if: runner.os != 'Windows'
        run: |
          strip target/${{ matrix.target }}/release/slow-query-converter${{ matrix.ext }}

      - name: Strip binary (Windows)
        if: runner.os == 'Windows'
        run: |
          # Use the built-in strip tool on Windows
          if (Test-Path "target/${{ matrix.target }}/release/slow-query-converter${{ matrix.ext }}") {
            # Skip stripping on Windows as it's not critical and the tool may not be available
            Write-Host "Binary built successfully, skipping strip on Windows"
          }

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: slow-query-converter-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/slow-query-converter${{ matrix.ext }}

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create checksums
        run: |
          cd artifacts
          echo "=== Creating Checksums ==="
          # Find all binary files in artifact directories
          for artifact_dir in slow-query-converter-*; do
            if [ -d "$artifact_dir" ]; then
              echo "Processing directory: $artifact_dir"
              # Find any file in the directory (should be the binary)
              binary_file=$(find "$artifact_dir" -type f | head -1)
              echo "Found binary file: $binary_file"
              
              if [ -f "$binary_file" ]; then
                sha256sum "$binary_file" > "$binary_file.sha256"
                echo "✅ Created checksum for: $binary_file"
                
                # Verify the checksum file was created
                if [ -f "$binary_file.sha256" ]; then
                  echo "✅ Checksum file verified"
                else
                  echo "❌ Checksum file not created"
                fi
              else
                echo "❌ No binary file found in $artifact_dir"
                echo "Directory contents:"
                ls -la "$artifact_dir"
              fi
            fi
          done

      - name: Debug artifacts
        run: |
          echo "Artifacts structure:"
          find artifacts -type f -name "*slow-query-converter*" | head -20
          echo "File sizes:"
          ls -la artifacts/*/slow-query-converter* 2>/dev/null || echo "No files found"
          
      - name: Prepare release files
        run: |
          # Create a clean release directory
          mkdir -p release-files
          
          # Copy and rename files for better organization
          # The artifacts are organized as: artifacts/artifact-name/binary-file
          for artifact_dir in artifacts/slow-query-converter-*; do
            if [ -d "$artifact_dir" ]; then
              # Extract target from directory name
              target=$(basename "$artifact_dir")
              
              # Find any file in the directory (should be the binary)
              binary_file=$(find "$artifact_dir" -type f | head -1)
              
              if [ -f "$binary_file" ]; then
                # Copy binary
                cp "$binary_file" "release-files/${target}"
                
                # Copy checksum if exists
                if [ -f "${binary_file}.sha256" ]; then
                  cp "${binary_file}.sha256" "release-files/${target}.sha256"
                fi
                
                echo "Copied: $binary_file -> release-files/${target}"
              else
                echo "Warning: No binary found in $artifact_dir"
              fi
            fi
          done
          
          echo "Release files prepared:"
          ls -la release-files/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: MariaDB Slow Query to CSV Converter ${{ github.ref_name }}
          body: |
            ## 🚀 MariaDB Slow Query to CSV Converter ${{ github.ref_name }}

            A high-performance Rust utility to parse MariaDB slow query logs and convert them into clean, multiline CSV format.

            ### 📦 Downloads

            **Linux (x86_64)**: `slow-query-converter-x86_64-unknown-linux-gnu`
            **Windows (x64)**: `slow-query-converter-x86_64-pc-windows-msvc.exe`
            **macOS (Intel)**: `slow-query-converter-x86_64-apple-darwin`
            **macOS (Apple Silicon)**: `slow-query-converter-aarch64-apple-darwin`

            ### 🛠️ Usage

            ```bash
            # Make executable (Unix)
            chmod +x slow-query-converter-*
            
            # Convert to CSV file
            ./slow-query-converter-* -i slow.log -o output.csv
            
            # Output to stdout
            ./slow-query-converter-* -i slow.log
            ```

            ### 📝 Features

            - **Fast Processing**: Optimized for large log files
            - **Multiline Query Support**: Handles multi-line SQL queries
            - **Metadata Extraction**: Separates SET timestamp and USE schema statements
            - **Flexible Output**: File or stdout output
            - **Clean CSV Format**: Excel-compatible output

            ### 🔗 Repository

            https://github.com/isaacnugroho/slow-query-converter

            ---

            **Checksums:**
            - All binaries include SHA256 checksums for verification
            - Use `sha256sum -c *.sha256` to verify integrity
          files: |
            release-files/slow-query-converter-*
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
